### ISSUE TITLE
Faith Ebert - 04 - Rationale - Just Your Type

### ISSUE THREAD

**Issue by faithebert** [faithebert/just-your-type#1]
@muxlowc

This was a very fun yet challenging project. I wanted to keep the fonts simple yet interesting with a good amount of contrast. I went with a simple, readable sans-serif font called _Kanit_ with a handful of weights, so that I could change it up that way without changing the font. For decorative touches, I chose a script font called _Parisienne_ to add interest and lightness to the design of the site, and I think since both of them are readable and fairly simple (respectively), they work harmoniously. The type scale I ended up choosing was Perfect Fourth with Major Third for the smaller screen sizes. I wanted larger contrast than the default font sizes on Typographier give and wanted to have fun with larger type, which pushed me outside of my comfort zone. I chose a blue colour scheme because this song has emotional, deep lyrics and wanted to match that tone while also providing an easily digestible colour palette. 

I effectively used grids and modular CSS by creating a clear plan and sticking to that. I had a good grasp of the classes and options available to me, so it was just a matter of pushing the limits of what I could do with that knowledge. I made my sketches with all the practice we had done in mind, meaning that I could easily use elements like positioning, alignment, text sizes, units, grids and many more to show that I have a good grasp on grids and modular CSS. This was overall a challenging project because I was only limited by my own mind, meaning I also had to learn when to reign it in as well. I struggled to find elements amongst all of the classes, but this gave me more practice with seeing the elements once the CSS was applied (classes) and it allowed for me to become faster in changing elements in HTML rather than having to keep switching to CSS (as we had before second semester). I scrapped one of my first trials where I was just getting used to sizing, fonts, etc. which is why .quote-1 is hidden. From this, I went on to create a product that I am proud of, after that design proved to be too complicated and just did not work for the web (it didn't look good at all). I learned a lot about myself as a designer and a coder over this project and am happy with how it turned out.

**Comment by muxlowc** [comment]
@faithebert you should be super proud of yourself - this is really great! And amazing use of everything you've learned in class so far :) 

By the way, I actually really like how your first quote turned out !
